alert('ERROR CODE : 966')
alert('귀하의 >>966<< 으로부터 계정이 해킹당했습니다  이 기기에서 하는 모든 행동이 해커에 의해서 감시됩니다.  즉각적인 조치가 필요합니다!   Your account has been hacked for >>966<<. Everything you do on this device is monitored by hackers. Immediate action is required!')
alert('끄끄끄끄끄끄끄끄끄.')
alert('어이, 뭐냐구 그 표정은? 끄끅.')
alert('설마 진짜 속은거야? 지롱♪ 끄~끄끄끄끄.')
alert('진짜 해킹한 건 아니니까 걱정 말라구.')
alert('진짜 속아서 처음부터 나가버린 사람은 없겠지? 끅!')
alert('뭐, 내 알 바 아니지만!')
alert('난 뭐, 볼 일 끝났으니까 가볼거지롱. 끄끅!')